openapi: 3.0.0
info:
  description: "API Rest avec Java et Spring Boot pour ajouter et obtenir les détails d'un film."
  version: "0.0.1"
  title: "Film API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "mounir.mahmoud@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
servers:
  - url: '{protocol}://localhost:8080/api'
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
paths:
  /film:
    post:
      tags:
        - "Film"
      summary: "Add a film in the database"
      operationId: "createFilm"
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Film'
      responses:
        "201":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Film"
  /film/{id}:
    get:
      tags:
        - "Film"
      summary: "Find film by ID in the database"
      description: "Returns a single film"
      operationId: "getFilmById"
      parameters:
        - name: id
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type : integer
            format: int64
            minimum: 1
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Film"

components:
  schemas:
    Film:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        titre:
          type: "string"
        description:
          type: "string"
        acteurs:
          type: array
          items:
            $ref: "#/components/schemas/Acteur"
    Acteur:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        name:
          type: "string"
        prenom:
          type: "string"
